version: '3'

services:
  api:
    build:
      context: ./app  # Points to the app directory
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/mydatabase"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"

  celery_worker:
    build:
      context: ./app  # Points to the app directory
      dockerfile: Dockerfile.celery  # Points to the Celery Dockerfile
    depends_on:
      - redis
      - db
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/mydatabase"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    command: celery -A celery_app worker --loglevel=info  # Command to start the Celery worker

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  db:
    image: "postgres:alpine"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
