# Use the official Python image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Set the PYTHONPATH environment variable
# ENV PYTHONPATH=/app

# Copy requirements.txt first to leverage Docker layer caching
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code into the container
COPY . .

# Command to run the Celery worker
CMD ["celery", "-A", "celery_app", "worker", "--loglevel=info"]
